version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  registries:
  - github-packages
  open-pull-requests-limit: 20
  schedule:
    interval: weekly
  groups:
    test-dependencies:
      patterns:
      - org.junit.*
      - org.mockito.*
    log4j:
      patterns:
      - org.apache.logging.*
registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/veupathdb/maven-packages
    username: ${{ secrets.PACKAGES_USER }}
    password: ${{ secrets.PACKAGES_KEY }}
