services:
  service:
    image: veupathdb/vdi-plugin-handler-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - '8080:80'
    volumes:
    - type: bind
      source: ./.tmp/mount
      target: /datasets
    environment:
      SERVER_PORT: 80
      SERVER_HOST: 0.0.0.0

      LDAP_SERVER: ${LDAP_SERVER:?}
      ORACLE_BASE_DN: ${ORACLE_BASE_DN:?}

      CHECK_COMPAT_SCRIPT_PATH: /bin/bash
      CHECK_COMPAT_SCRIPT_MAX_DURATION: 1h

      IMPORT_SCRIPT_PATH: /bin/bash
      IMPORT_SCRIPT_MAX_DURATION: 1h

      INSTALL_DATA_SCRIPT_PATH: /bin/bash
      INSTALL_DATA_SCRIPT_MAX_DURATION: 1h

      INSTALL_META_SCRIPT_PATH: /bin/bash
      INSTALL_META_SCRIPT_MAX_DURATION: 1h

      UNINSTALL_SCRIPT_PATH: /bin/bash
      UNINSTALL_SCRIPT_MAX_DURATION: 1h

      DATASET_INSTALL_ROOT: /datasets

      SITE_BUILD: build-68

      DB_CONNECTION_ENABLED_DEMO: true
      DB_CONNECTION_NAME_DEMO: PlasmoDB
      DB_CONNECTION_LDAP_DEMO: ${DB_CONNECTION_LDAP_DEMO:?}
      DB_CONNECTION_USER_DEMO: ${DB_CONNECTION_USER_DEMO:?}
      DB_CONNECTION_PASS_DEMO: ${DB_CONNECTION_PASS_DEMO:?}
      DB_CONNECTION_DATA_SCHEMA_DEMO: ${DB_CONNECTION_DATA_SCHEMA_DEMO:?}
      DB_CONNECTION_CONTROL_SCHEMA_DEMO: ${DB_CONNECTION_CONTROL_SCHEMA_DEMO:?}
