package vdi.consts

object FieldName {
  const val DataFiles = "dataFiles"
  const val Dependencies = "dependencies"
  const val Description = "description"
  const val Details = "details"
  const val InputFiles = "inputFiles"
  const val JobID = "jobID"
  const val Message = "message"
  const val Meta = "meta"
  const val Name = "name"
  const val Owner = "owner"
  const val Payload = "payload"
  const val ProjectID = "projectID"
  const val Projects = "projects"
  const val ResourceIdentifier = "resourceIdentifier"
  const val ResourceVersion = "resourceVersion"
  const val ResourceDisplayName = "resourceDisplayName"
  const val Summary = "summary"
  const val Type = "type"
  const val VDIID = "vdiID"
  const val Version = "version"
  const val Warnings = "warnings"
}
