name: Publish Release Artifacts

on:
  push:
    tags:
    - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: corretto
    - uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
    - name: Build
      run: |
        ./gradlew --no-daemon clean test shadowJar
        mv -t . service/build/libs/service.jar
        sha256sum service.jar | cut -f1 -d' ' -z > service.jar.sha256
        md5sum service.jar | cut -f1 -d' ' -z > service.jar.md5
      env:
        GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: false
        files: |
          service.jar
          service.jar.sha256
          service.jar.md5
        generate_release_notes: true
